# vim:fileencoding=utf-8:foldmethod=marker


font_family      family='Twilio Sans Mono' postscript_name=TwilioSansMono-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
hide_window_decorations no
# YES HIDES TITLEBAR
# hide_window_decorations no


cursor_trail 9
cursor_trail_decay 0.1 0.4

background_opacity 0.95
#background_blur 50

window_border_width 1pt
draw_minimal_borders yes

tab_bar_edge top
tab_bar_align center
tab_bar_style separator
# tab_separator " • "
tab_separator " | "
tab_bar_margin_height 0.0 0.0
tab_title_max_length 30
tab_title_template "{title.split(' ')[0]}"

window_padding_width 1 1 1
window_margin_width 1 1 1

shell_integration enabled

# WINDOW LAYOUTS - splits and stacks
enabled_layouts splits,stack
# Campbell
include current-theme.conf
# Detach current split into a new OS window
map ctrl+shift+d detach_window
# Detach current split into a new tab instead
map ctrl+shift+alt+d detach_window new-tab
map ctrl+shift+alt+w detach_window tab-prev
map ctrl+shift+alt+f4 detach_window ask
map ctrl+shift+h launch --cwd=current --location=hsplit
map ctrl+shift+j launch --cwd=current --location=vsplit

allow_remote_control yes
listen_on unix:@mykitty
shell /usr/bin/fish
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B7,U+E700-U+E8EF,U+EA60-U+EC1E,U+ED00-U+EFCE,U+F000-U+F2FF,U+F300-U+F381,U+F400-U+F533,U+F0001-U+F1AF0 JetBrainsMono Nerd Font Mono
